---
- hosts: localhost
  become: yes
  tasks:

  - name: Pause for 1 minutes to build app cache
    pause:
      minutes: 1

- hosts: localhost
  gather_facts: yes
  become: yes
  roles: 
    - elastic-search

- hosts: localhost
  gather_facts: yes
  become: yes
  roles: 
    - elastic-search-slave
